# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '2nd_seminar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 2nd_seminar
pod 'CHIPageControl', '~> 0.1.3'

end
